package wawi.gui.kundegui.gui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import wawi.fachlogik.kundesteuerung.grenzklassen.BestellungGrenz;
import wawi.fachlogik.kundesteuerung.grenzklassen.BestellungspositionGrenz;
import wawi.fachlogik.kundesteuerung.grenzklassen.KundeGrenz;
import wawi.fachlogik.kundesteuerung.impl.IActivateComponentImpl;
import wawi.fachlogik.kundesteuerung.impl.IKundeSteuerungBestellungImpl;
import wawi.fachlogik.kundesteuerung.service.IKundeSteuerungBestellung;

public class EigeneBestellungen extends javax.swing.JFrame {

    private KundeGrenz kunde;
    private IKundeSteuerungBestellung kundeSteuerungBestellung;

    public EigeneBestellungen(FrameKunde parent) {
        initComponents();
        this.kunde = IActivateComponentImpl.kunde;
        try {
            kundeSteuerungBestellung = new IKundeSteuerungBestellungImpl();
        } catch (Exception ex) {
            Logger.getLogger(EigeneBestellungen.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame) e.getSource();

                int result = JOptionPane.showConfirmDialog(frame, "Bestellungs Verwaltung wirklich schließen?", "Bestellungs Verwaltung", JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION) {
                    parent.changeEBestellungenBtnStatus(true);
                    frame.dispose();
                }
            }
        });

        setBestellungen();
    }

    private void setBestellungen() {
        DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();
        DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
        root.removeAllChildren();
        jTree1.setRootVisible(false);
        List<BestellungGrenz> bestellungen = kundeSteuerungBestellung.getBestellungListe(kunde.getKid());

        for (BestellungGrenz b : bestellungen) {
            String nodeText = "ID: " + b.getBid() + " - Status: " + b.getStatus().name() + " - Lieferadr.: " + b.getLieferadresse() + " - Rechnungsadr.: " + b.getRechnungsadresse() + " - Angelegt: " + b.getAngelegt() + " - Gesamtbrutto: " + b.getGesamtBrutto().toString() + " - Gesamtnetto: " + b.getGesamtNetto().toString();
            DefaultMutableTreeNode node = new DefaultMutableTreeNode(nodeText);
            for (BestellungspositionGrenz bpos : b.getBestellungspositionsList()) {
                String subNodeText = "BPOS ID: " + bpos.getBpid() + " - Anzahl: " + bpos.getAnzahl() + " - Produkt Name: " + bpos.getProdukt().getName() + " - Einzel-Nettopreis: " + bpos.getProdukt().getNettopreis();
                DefaultMutableTreeNode subNode = new DefaultMutableTreeNode(subNodeText);
                node.add(subNode);
            }
            root.add(node);
        }
        model.reload();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Bestellungs Verwaltung");
        setMaximumSize(new java.awt.Dimension(1372, 676));
        setMinimumSize(new java.awt.Dimension(1372, 676));
        setType(java.awt.Window.Type.UTILITY);

        jButton1.setText("Storniere selektierte Bestellung");
        jButton1.setToolTipText("Setze die aktuell ausgewählte Bestellung auf Stoniert (wenn möglich)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTree1);

        jButton2.setText("Aktualisiere Bestellungen");
        jButton2.setToolTipText("Setze die aktuell ausgewählte Bestellung auf Stoniert (wenn möglich)");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1020, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();

        if (selectedNode == null) // Keine node ausgewählt
        {
            JOptionPane.showOptionDialog(null, "Fehler: Sie müssen zuerst eine Bestellung auswählen!", "Bestellungs Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
        }
        else if (selectedNode.isLeaf())
        {
            if (selectedNode.getLevel() == 1)
            {
                JOptionPane.showOptionDialog(null, "Fehler: Diese Bestellung ist fehlerhaft und besitzt keine Bestellungspositionen. Bitte Kontaktieren Sie den System-Administrator.", "Bestellungs Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
            }
            else 
            {
                JOptionPane.showOptionDialog(null, "Fehler: Wählen Sie bitte die Bestellung und nicht die Bestellungsposition an!", "Bestellungs Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
            }
        }
        else {
            String nodeText = (String) selectedNode.getUserObject();
            int bid = Integer.valueOf(nodeText.substring(4, nodeText.indexOf("-")).trim());
            boolean result = kundeSteuerungBestellung.storniereBestellung(bid);
            if (result) {
                JOptionPane.showOptionDialog(null, "Erfolg: Ihre gewählte Bestellung wurde storniert!", "Bestellungs Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"OK"}, "OK");
                setBestellungen();
            } else {
                JOptionPane.showOptionDialog(null, "Fehler: Die Bestellung konnte nicht storniert werden.", "Bestellungs Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setBestellungen();
        JOptionPane.showOptionDialog(null, "Die Bestellungen wurden aktualisiert!", "Bestellungs Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"OK"}, "OK");
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
