package wawi.gui.kundegui.gui;

import wawi.fachlogik.kundesteuerung.grenzklassen.KundeGrenz;
import wawi.fachlogik.kundesteuerung.impl.IActivateComponentImpl;

public class FrameKunde extends javax.swing.JFrame {

    private KundeGrenz kunde;

    public FrameKunde() {
        initComponents();

        this.kunde = IActivateComponentImpl.kunde;

        setKundeMeta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Kunde - Hauptfenster");
        setMaximumSize(new java.awt.Dimension(694, 227));
        setMinimumSize(new java.awt.Dimension(694, 227));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jButton1.setText("Bestellung anlegen");
        jButton1.setToolTipText("Hier haben Sie die Möglichkeit neue Bestellungen anzulegen.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Bestellungs Verwaltung Öffnen");
        jButton2.setToolTipText("Zeigt eine Liste aller eigenen Bestellungen an, noch nicht vershickte Bestellungen können hier Storniert werden.");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Nachrichten Verwaltung Öffnen");
        jButton3.setToolTipText("Zeigt eine Liste aller Nachrichten an und ermöglicht das versenden/lesen/löschen von Nachrichten.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Willkommen im Kundenbereich des TH Warenwirtschaftssystems.\n\n\nHier können Sie unter anderem eine neue Bestellung anlegen\n\noder sich eine Übersicht Ihrer aktuellen Bestellungen anzeigen lassen.\nEine nicht verschickte Bestellung können Sie in diesem Bereich stornieren.\n\nAuch haben Sie die Möglichkeit hier Ihre Nachrichten zu verwalten.\nIn diesem Bereich können Sie Nachrichten senden, auf gelesen setzen\nund löschen.");
        jTextArea1.setToolTipText("Hovern Sie über die Buttons für mehr Informationen!");
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusable(false);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Eingeloggt als:");

        jLabel2.setText("n/a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(13, 13, 13)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setKundeMeta() {
        jLabel2.setText("(id: " + kunde.getKid() + ") " + kunde.getVorname() + " " + kunde.getName());
    }

    public void changeNeueBestellungBtnStatus(boolean flag) {
        jButton1.setEnabled(flag);
    }

    public void changeEBestellungenBtnStatus(boolean flag) {
        jButton2.setEnabled(flag);
    }

    public void changeNachrichtenBtnStatus(boolean flag) {
        jButton3.setEnabled(flag);
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NeueBestellung nBestellungen = new NeueBestellung(this);
        nBestellungen.setVisible(true);
        changeNeueBestellungBtnStatus(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        EigeneBestellungen eBestellungen = new EigeneBestellungen(this);
        eBestellungen.setVisible(true);
        changeEBestellungenBtnStatus(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Nachrichten nachrichten = new Nachrichten(this);
        nachrichten.setVisible(true);
        changeNachrichtenBtnStatus(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
