package wawi.gui.kundegui.gui;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import wawi.fachlogik.kundesteuerung.grenzklassen.KundeGrenz;
import wawi.fachlogik.kundesteuerung.grenzklassen.NachrichtGrenz;
import wawi.fachlogik.kundesteuerung.impl.IActivateComponentImpl;
import wawi.fachlogik.kundesteuerung.impl.IKundeSteuerungNachrichtImpl;
import wawi.fachlogik.kundesteuerung.service.IKundeSteuerungNachricht;
import javax.swing.*;

public class Nachrichten extends javax.swing.JFrame {

    private KundeGrenz kunde;
    private IKundeSteuerungNachricht kundeSteuerungNachricht;
    private boolean shown;

    public Nachrichten(FrameKunde parent) {
        shown = false;
        initComponents();
        try {
            kundeSteuerungNachricht = new IKundeSteuerungNachrichtImpl();
        } catch (Exception ex) {
            Logger.getLogger(Nachrichten.class.getName()).log(Level.SEVERE, null, ex);
        }

        jTable2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Nur eine Zeile darf auf einmal ausgewählt werden

        this.kunde = IActivateComponentImpl.kunde;

        getMessages(); // Update Messages

        // Ungelesene Nachrichten hervorheben (GRAY) und sonst bei gelesen nicht (LIGHT_GRAY)
        jTable2.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
                final Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                String status = (String) table.getModel().getValueAt(row, 2);
                c.setBackground(status.equals("ungelesen") ? Color.GRAY : Color.LIGHT_GRAY);
                return c;
            }
        });
        
              jTable2.addMouseListener(new MouseAdapter() {
         public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
               DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
               int selectedRowIdx = jTable2.getSelectedRow();
               String msg = (String) tableModel.getValueAt(selectedRowIdx, 3);
               TextFrame textFrame = new TextFrame(msg);
               textFrame.setVisible(true);
            }
         }
      });

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                JFrame frame = (JFrame) e.getSource();

                int result = JOptionPane.showConfirmDialog(frame, "Nachrichten Verwaltung wirklich schließen?", "Nachrichten Verwaltung", JOptionPane.YES_NO_OPTION);

                if (result == JOptionPane.YES_OPTION) {
                    parent.changeNachrichtenBtnStatus(true);
                    frame.dispose();
                }
            }
        });

        shown = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Nachrichten Verwaltung");
        setMaximumSize(new java.awt.Dimension(1109, 562));
        setMinimumSize(new java.awt.Dimension(1109, 562));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Betreff", "Status", "Nachricht", "Angelegt", "Typ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Nachrichten Abrufen");
        jButton1.setToolTipText("Ruft alle Nachrichten aus der Datenbank für Sie ab");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Selektierte Nachricht löschen");
        jButton2.setToolTipText("Lösche die aktuell ausgewählte Nachricht");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Neue Nachricht erstellen");
        jButton4.setToolTipText("Erstelle eine neue Nachricht");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nachricht als gelesen setzen");
        jButton5.setToolTipText("Setze die aktuell ausgewählte Nachricht auf gelesen");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Merke: Mit einem Doppelklick auf die einzelnen Zeilen öffnet sich ein extra Fenster mit der formattierten Nachricht!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void getMessages() {
        List<NachrichtGrenz> items = kundeSteuerungNachricht.nachrichtenAbrufen(kunde.getKid());
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        tableModel.setRowCount(0); // Alle Zeilen "loeschen"

        for (NachrichtGrenz msg : items) {
            tableModel.addRow(
                    new Object[]{
                        msg.getNid(),
                        msg.getBetreff(),
                        msg.getStatus().name(),
                        msg.getNachricht(),
                        msg.getAngelegt().toString(),
                        msg.getTyp().name()
                    });
        }

        if (shown) {
            JOptionPane.showOptionDialog(null, "Ihre Nachrichten wurden abgerufen. Es wurden " + items.size() + " abgerufen.", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"OK"}, "OK");
        }
    }

    // Nachrichten Abrufen Btn
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        getMessages();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        int selectedRowIdx = jTable2.getSelectedRow();

        if (selectedRowIdx < 0) {
            JOptionPane.showOptionDialog(null, "Fehler: Sie haben keine Nachricht ausgewaehlt die geloescht werden soll!", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
        } else {
            int nid = (int) tableModel.getValueAt(selectedRowIdx, 0); // selectedRow Index, 0 ( = Nachrichten ID)
            boolean result = kundeSteuerungNachricht.loescheNachricht(nid);
            if (result) {
                JOptionPane.showOptionDialog(null, "Erfolg! Ihre Nachricht wurde gelöscht", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"OK"}, "OK");
                tableModel.removeRow(selectedRowIdx);
            } else {
                JOptionPane.showOptionDialog(null, "Fehler! Ihre Nachricht konnte nicht gelöscht werden!", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        NachrichtErstellen nErstellen = new NachrichtErstellen(this);
        shown = false;
        nErstellen.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        int selectedRowIdx = jTable2.getSelectedRow();

        if (selectedRowIdx < 0) {
            JOptionPane.showOptionDialog(null, "Fehler: Sie haben keine Zeile ausgewaehlt die geloescht werden soll!", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
        } else {
            int nid = (int) tableModel.getValueAt(selectedRowIdx, 0); // selectedRow Index, 0 ( = Nachrichten ID)
            boolean result = kundeSteuerungNachricht.setNachrichtGelesen(nid);
            if (result) {
                JOptionPane.showOptionDialog(null, "Erfolg! Ihre ausgewählte Nachricht wurde als gelesen markiert", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.INFORMATION_MESSAGE, null, new Object[]{"OK"}, "OK");
                shown = false;
                getMessages();
                shown = true;
            } else {
                JOptionPane.showOptionDialog(null, "Fehler! Ihre Nachricht konnte nicht auf gelesen gesetzt werden! Merke: Sie können nur Nachrichten, die an Sie adressiert sind als gelesen markieren!", "Nachrichten Verwaltung", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE, null, new Object[]{"OK"}, "OK");
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    public void setShown(boolean value) {
        shown = value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}

class TextFrame extends JFrame
{
   public TextFrame(String content) {
      super("Nachrichten Text");
  
      JTextArea ta = new JTextArea();
      ta.setEditable(false);
      ta.setLineWrap(true);
      ta.setWrapStyleWord(true);
      ta.setText(content);
      getContentPane().add(ta);
      addWindowListener(new WindowAdapter() {
         public void windowClosing(WindowEvent we) {
            dispose();
         }
      });
       
      setSize(640, 480);
   }
}